-- AlterTable
ALTER TABLE "SubVendo" ADD COLUMN     "connectedClients" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "freeMemory" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "online" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "temperature" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "uptime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "wifiSignal" INTEGER NOT NULL DEFAULT 0;
